check_prop: 0.01
gpu_num: 4
epochs: 100
model_name: saibr
data_name: ETTm1
model_save_path: ./checkpoints/${data_name}

ddp:
  do: false
  kwargs:
    nprocs: 3
    join: true

wandb:
  do: true
  kwargs:
    project: logging_practice
    name: ${data_name}/${model_name}

dataset:
  root: ./data/ETT-small/ETTm1.csv
  window_size: 96
  mask_prob: 0.4

dataloader:
  train:
    batch_size: 32
    shuffle: true

  val:
    batch_size: 128
    shuffle: false

early_stopping:
  val_key: val mae
  tolerance: 5
  higher_better: false

model:
  hid_dim: 3
  n_layers: 1
  num_heads: 1
  loss_kwargs: {}
  val_loss_kwargs:
    reduction: sum

optimizer:
  lr: 0.001